// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABDFb8C9jp5ulgYz330effeZ3ViG6FSmA',
    appId: '1:535076446983:web:e3fc5e721f24fdd4a01ba2',
    messagingSenderId: '535076446983',
    projectId: 'inclass16-ce3ac',
    authDomain: 'inclass16-ce3ac.firebaseapp.com',
    storageBucket: 'inclass16-ce3ac.firebasestorage.app',
    measurementId: 'G-M1SDGLEH2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDPK6_Lb8id23uGDOYlpU_2fnHCVGkTIs',
    appId: '1:535076446983:android:01fc4e1ffddb434ca01ba2',
    messagingSenderId: '535076446983',
    projectId: 'inclass16-ce3ac',
    storageBucket: 'inclass16-ce3ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN-J_vV3fw35T5IKDjupCI96IMyUgDauI',
    appId: '1:535076446983:ios:2111caff09e68485a01ba2',
    messagingSenderId: '535076446983',
    projectId: 'inclass16-ce3ac',
    storageBucket: 'inclass16-ce3ac.firebasestorage.app',
    iosBundleId: 'com.example.inclass16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN-J_vV3fw35T5IKDjupCI96IMyUgDauI',
    appId: '1:535076446983:ios:2111caff09e68485a01ba2',
    messagingSenderId: '535076446983',
    projectId: 'inclass16-ce3ac',
    storageBucket: 'inclass16-ce3ac.firebasestorage.app',
    iosBundleId: 'com.example.inclass16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABDFb8C9jp5ulgYz330effeZ3ViG6FSmA',
    appId: '1:535076446983:web:af1ad15aee1fe11ea01ba2',
    messagingSenderId: '535076446983',
    projectId: 'inclass16-ce3ac',
    authDomain: 'inclass16-ce3ac.firebaseapp.com',
    storageBucket: 'inclass16-ce3ac.firebasestorage.app',
    measurementId: 'G-1KH83R4VPZ',
  );
}
